### ISSUE TITLE
Enhancement discussion

### ISSUE THREAD

**Issue by arsonistgopher** [hihebark/pickle#5]
Hi,

I've started using Pickle quite frequently because of its' ease of use. 
When writing any documents with logic to be expressed, I include flow diagrams written in UML (yUML) and was wondering if there is a discussion to be had here about including a yUML diagram generator as part of Pickle, or at least an integration?

Thanks

**Comment by hihebark** [comment]
**Thank's you**, i will see what i can do about it. i don't have time now but will see.

**Comment by arsonistgopher** [comment]
Hey, thanks for the response. If I grab some time, I can take a stab and do a PR for review/scrutiny if you're up for that? I think it would be quite a useful addition. I use Pickle now for most customer interactions and would benefit me (quite selfishly) possibly the most at this point. Let me know your thoughts.

**Comment by hihebark** [comment]
i created a branch __yUML-integration__ to work on it!

**Comment by hihebark** [comment]
refer to this d606016ecab900d829524eee78207e096136b40a

**Comment by hihebark** [comment]
Just testing but i found a simple way to do that is to write:
```yuml
[Directional]->[Class]
```
then pickle will convert this code form into this
![Association schema](http://yuml.me/diagram/scruffy/class/[Directional]->[Class])
but it work only with class's.
if you can, post a simple code of how do you use **yuml** to understand how to do this.
